# Numpy

- Stands for Numerical Python and is the Core library for numerical computations
- Provides functionalities to make multi-dimensional arrays (1D, 2D, 3D or nD arrays)


- We have lists that we can use to create multi-dimensional lists instead of using arrays to perform these tasks, so why do we need Numpy?


- The advantages of using Numpy is Memory efficient, Faster, lot of convenience and functionalties.
- Numpy is built on C language which makes it so much faster.

Numpy contains `integers` and `floating point objects` and also some `containers like Lists and Dictionaries` built-in for faster mathematical calculations

In NumPy, dimensions are called **axis**. In the 2-d array above, there are two axis, having two and three elements respectively. 

In NumPy terminology, for 2-D arrays:
* ```axis = 0``` refers to the axis running vertically downwards across rows
* ```axis = 1``` refers to the axis running horizontally across columns

# Data Manipulation

In [3]:
import numpy as np

# Creating array from list and tuple

In [12]:
lst =[1,2,3,4,5,6,7,8]
lst

[1, 2, 3, 4, 5, 6, 7, 8]

In [13]:
import numpy as np
arr1 = np.array(lst)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
lst = [1,2,3,4,5,6,7,8]
arr = np.array(lst)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
tup = (1,2,3,4,5,6)
arr = np.array(tup)
arr

array([1, 2, 3, 4, 5, 6])

In [18]:
arr1.ndim

1

In [19]:
arr1.shape

(8,)

# Creating 2-d Array

In [23]:
arr_2d = np.array([[1,2,3,4],[4,5,6,7]])
arr_2d

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

# 1D Array is called Vector, 2D Array is called Matrix, nD Array is called Tensor 

# Creating arrays using functions

The other common way is to initialise arrays using built-in functions. 

The following ways are commonly used:
* ```np.ones()```: Create array of 1s
* ```np.zeros()```: Create array of 0s
* ```np.random.random()```: Create array of random numbers
* ```np.arange()```: Create array with increments of a fixed step size
* ```np.linspace()```: Create array of fixed length
* ```np.diag()```: Constructs a diagonal array

In [7]:
import numpy as np
arr_2d = np.array([[1,2,3,4],[4,5,6,7]])
arr_2d

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [8]:
print(arr_2d.ndim)

2


In [6]:
print(arr_2d.shape)

(2, 4)


In [17]:
arr2 = np.arange(5,51,5, dtype = 'float')
arr2

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [14]:
arr2.ndim

1

above querry results showing 25., because it is float values so shows decimals.

In [19]:
np.ones((5,5),dtype = 'int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [2]:
np.zeros((5,4),dtype = 'int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [15]:
np.arange(32).reshape(8,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [15]:
np.full((5,5),23)

array([[23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23]])

In [38]:
np.full((5,5), 23.5)

array([[23.5, 23.5, 23.5, 23.5, 23.5],
       [23.5, 23.5, 23.5, 23.5, 23.5],
       [23.5, 23.5, 23.5, 23.5, 23.5],
       [23.5, 23.5, 23.5, 23.5, 23.5],
       [23.5, 23.5, 23.5, 23.5, 23.5]])

In [16]:
np.random.randint(100,500, size = (5,5))

array([[164, 162, 467, 214, 281],
       [462, 400, 123, 147, 311],
       [354, 238, 221, 391, 395],
       [285, 436, 114, 127, 312],
       [491, 139, 456, 468, 432]])

In [21]:
np.random.randint(-100,500, size = (6,3))

array([[-64, -40, -90],
       [240, 335, 319],
       [479, 329, 231],
       [116, 358, 373],
       [ 14, 317, 194],
       [143, 224, 311]])

In [6]:
import numpy as np
np.random.randint(-10,10, size =(3,3))

array([[ 9,  2, -8],
       [-9,  1,  8],
       [-6,  7,  4]])

# Basic DataTypes

#You can explicitly specify which data-type you want:

a_float = np.arange(15, dtype='float')
a_float

In [7]:
#The default data type is float for zeros and ones function

a = np.ones((3, 3), dtype='int')

print(a)
a.dtype

[[1 1 1]
 [1 1 1]
 [1 1 1]]


dtype('int64')

In [8]:
np_zeros = np.zeros((5,5), dtype='int')
np_zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# Some Other Datatypes in Numpy Arrays

In [9]:
d = np.array([1+2j, 2+4j])   #Complex datatype
d
#print(d.dtype)

array([1.+2.j, 2.+4.j])

In [10]:
b = np.array([True, False, True, False])  #Boolean datatype
b
#b.dtype

array([ True, False,  True, False])

In [11]:
s = np.array(['Ram', 'Robert', 'Rahim'])
s
#s.dtype

array(['Ram', 'Robert', 'Rahim'], dtype='<U6')

# Indexing and Slicing

# Indexing in array

<font size = '5'>The items of an array can be accessed and assigned to the same way as other **Python sequences (e.g. lists)**</font>

<font size = '3'> For multiple Dimensional Arrays, indexes are tuples of integers.</font>

In [4]:
arr = np.arange(10,91,10, dtype = 'int').reshape(3,3)
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [13]:
arr[1,1]

50

In [5]:
arr[0,1]

20

# Slicing in array

In [15]:
arr[0:2,0:2]

array([[10, 20],
       [40, 50]])

In [16]:
arr[1:3,1:3]

array([[50, 60],
       [80, 90]])

In [17]:
arr[1,0:3]

array([40, 50, 60])

<font size = '5'>**Array Mathematics**</font>

In [18]:
lst=[1,2,3,4,5,6,7]
lst*2

[1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7]

In [2]:
lst=[1,2,3,4,5,6,7]
lst*2
lst2 = []
for i in lst:
    lst2.append(i*2)
lst2

[2, 4, 6, 8, 10, 12, 14]

In array we can do this in easy way.

In [21]:
arr = np.array(lst)
arr
arr*2

array([ 2,  4,  6,  8, 10, 12, 14])

In [22]:
arr2 = np.arange(1,10).reshape(3,3)
arr3 = np.arange(11,20).reshape(3,3)

In [23]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr3

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [32]:
arr2*5

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [33]:
arr3*3

array([[33, 36, 39],
       [42, 45, 48],
       [51, 54, 57]])

In [28]:
arr2*arr3

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

# matrix multiplication

In [31]:
arr2.dot(arr3)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [34]:
arr3-arr2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [35]:
arr2+arr3

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [40]:
np.add(arr2,arr3)

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [41]:
np.subtract(arr3,arr2)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [42]:
np.multiply(arr2,arr3)

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [46]:
np.divide(arr2,arr3)

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

In [47]:
np.exp(arr2)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [36]:
np.log(arr2)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [48]:
np.log(2)

0.6931471805599453

In [51]:
arr4 = np.random.randint(10,50, size = (10,8))
arr4

array([[47, 42, 34, 27, 48, 17, 48, 26],
       [22, 48, 35, 26, 31, 45, 24, 24],
       [29, 37, 26, 47, 44, 24, 21, 37],
       [12, 18, 46, 13, 24, 11, 26, 22],
       [40, 45, 40, 31, 19, 46, 47, 32],
       [30, 42, 40, 35, 47, 28, 16, 37],
       [31, 14, 49, 15, 23, 49, 30, 14],
       [46, 20, 41, 17, 28, 45, 26, 43],
       [37, 32, 17, 21, 41, 45, 25, 31],
       [47, 46, 44, 45, 27, 25, 47, 19]])

In [53]:
np.mean(arr4)

32.45

# axis = 0 is for coln.

In [54]:
np.mean(arr4, axis = 0)

array([34.1, 34.4, 37.2, 27.7, 33.2, 33.5, 31. , 28.5])

# axis = 1 is for rows.

In [56]:
np.mean(arr4, axis = 1)

array([36.125, 31.875, 33.125, 21.5  , 37.5  , 34.375, 28.125, 33.25 ,
       31.125, 37.5  ])

In [58]:
np.median(arr4, axis = 0)

array([34. , 39.5, 40. , 26.5, 29.5, 36.5, 26. , 28.5])

In [60]:
np.min(arr4, axis = 1)

array([17, 22, 21, 11, 19, 16, 14, 17, 17, 19])

In [61]:
np.max(arr4, axis = 0)

array([47, 48, 49, 47, 48, 49, 48, 43])

In [64]:
np.median(arr4[:2,4:8], axis =1)

array([37. , 27.5])

In [66]:
np.sort(arr4, axis = 0)

array([[12, 14, 17, 13, 19, 11, 16, 14],
       [22, 18, 26, 15, 23, 17, 21, 19],
       [29, 20, 34, 17, 24, 24, 24, 22],
       [30, 32, 35, 21, 27, 25, 25, 24],
       [31, 37, 40, 26, 28, 28, 26, 26],
       [37, 42, 40, 27, 31, 45, 26, 31],
       [40, 42, 41, 31, 41, 45, 30, 32],
       [46, 45, 44, 35, 44, 45, 47, 37],
       [47, 46, 46, 45, 47, 46, 47, 37],
       [47, 48, 49, 47, 48, 49, 48, 43]])

<font size='5'>Concatenate is a generalised function</font>

<font size='4'>Whereas vstack and hstack are specific function</font>

In [68]:
np.concatenate((arr3,arr2), axis = 0)

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [74]:
np.vstack((arr3,arr2))

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [76]:
np.concatenate((arr2,arr3), axis = 1)

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [71]:
np.hstack((arr2,arr3))

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [7]:
big_arr = np.random.randint(10,50, size=(10,8))
big_arr

array([[21, 30, 15, 46, 41, 40, 44, 38],
       [17, 31, 16, 44, 11, 15, 13, 21],
       [42, 37, 15, 32, 23, 13, 43, 29],
       [29, 24, 41, 34, 42, 23, 24, 25],
       [18, 28, 17, 33, 29, 10, 39, 22],
       [15, 44, 48, 30, 27, 20, 34, 18],
       [23, 43, 38, 20, 35, 30, 18, 47],
       [25, 42, 45, 41, 30, 38, 44, 21],
       [18, 35, 27, 21, 47, 24, 32, 25],
       [46, 24, 33, 30, 36, 29, 26, 48]])

In [88]:
np.vsplit(big_arr,5)

[array([[39, 24, 25, 25, 36, 39, 42, 35],
        [36, 22, 30, 40, 45, 30, 35, 48]]),
 array([[34, 47, 18, 10, 15, 29, 46, 25],
        [42, 42, 26, 29, 32, 26, 36, 21]]),
 array([[17, 35, 39, 20, 18, 44, 40, 32],
        [30, 27, 13, 39, 32, 19, 45, 33]]),
 array([[45, 36, 28, 27, 34, 40, 22, 33],
        [17, 39, 23, 29, 38, 15, 39, 37]]),
 array([[35, 41, 28, 42, 45, 32, 44, 44],
        [41, 11, 34, 38, 12, 41, 32, 18]])]

In [8]:
np.hsplit(big_arr, 4)

[array([[21, 30],
        [17, 31],
        [42, 37],
        [29, 24],
        [18, 28],
        [15, 44],
        [23, 43],
        [25, 42],
        [18, 35],
        [46, 24]]),
 array([[15, 46],
        [16, 44],
        [15, 32],
        [41, 34],
        [17, 33],
        [48, 30],
        [38, 20],
        [45, 41],
        [27, 21],
        [33, 30]]),
 array([[41, 40],
        [11, 15],
        [23, 13],
        [42, 23],
        [29, 10],
        [27, 20],
        [35, 30],
        [30, 38],
        [47, 24],
        [36, 29]]),
 array([[44, 38],
        [13, 21],
        [43, 29],
        [24, 25],
        [39, 22],
        [34, 18],
        [18, 47],
        [44, 21],
        [32, 25],
        [26, 48]])]