<font size = 5>Initialize an array 'x' x 'y' dimension with 0</font>

In [2]:
import numpy as np
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

<font size = 5>Arranging the number between x and y with interval of z</font>

In [8]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [10]:
# even numbers between 10 and 20
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

<font size = 5>Arranging z numbers between x and y</font>

In [11]:
np.linspace(5,10,10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [13]:
# even numbers from 0 to 10
np.linspace(0,10,6, dtype=int)

array([ 0,  2,  4,  6,  8, 10])

<font size = 5>Filling same number in array of dimension x x y</font>

In [15]:
np.full((3,2),12)

array([[12, 12],
       [12, 12],
       [12, 12]])

In [16]:
np.full((3,3),6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

<font size = 5>Filling random number in array of dimension x x y</font>

In [17]:
np.random.random((3,3))

array([[0.5244085 , 0.80539479, 0.35147179],
       [0.4130395 , 0.29422956, 0.85092002],
       [0.1350724 , 0.92003945, 0.85784843]])

In [18]:
np.random.randint(100,500,size=(3,3))

array([[397, 267, 231],
       [105, 345, 393],
       [169, 205, 397]])

<font size = 5>Numpy array inspection</font>

<font size = 5>Filling same number in array of dimension x x y</font>

<font size = 5>Inspection the array: Checking the size of array</font>

<font size = 5>ndarray.shape</font>

<font size =4>'return a tuple consisting of array dimension. Can also be used to resize.'</font>

In [40]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a.shape

(2, 4)

In [25]:
a = np.array([[1,2,3,4],[5,6,7,8],[2,3,4,5]])
a.shape

(3, 4)

<font size = 5>Inspection the array: Resizing the array</font>

In [29]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a.shape = (4,2)
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [32]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a.shape = (8,1)                         ## trick : x*y = total number of elements in the array 
a

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

<font size = 5>Return the dimesnion of array</font>

In [37]:
a = np.arange(24)
a.ndim              # #1
# # reshape our array
b = a.reshape(12,2)                    # # trick : Caclculate the factors of 24 : 1,2,3,4,6,8,12,24
b.ndim
b

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

<font size = 5>Find the number of elements in array</font>

In [38]:
a.size

24

In [39]:
d = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
d.size

12

<font size = 5>Finding datatype of array</font>

<font size = 5>ndarray.dtype</font>

In [47]:
a = np.arange(24)
a.dtype
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [46]:
a = np.arange(24.456,dtype = float)
a.dtype
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

<font size = 6>Numpy array mathematics</font>

<font size = 5>Addition</font>

In [4]:
np.sum([10,20])

30

In [5]:
# # using variables
a = 10
b = 20
np.sum([a,b])

30

In [6]:
np.add(a,b)

30

In [9]:
np.sum([[1,2],[5,6]],axis=0)

array([6, 8])

In [11]:
np.sum([[1,2],[5,6]],axis=1)

array([ 3, 11])

In [13]:
np.sum([[1,2],[5,6]])

14

<font size = 5>Subtraction</font>

In [14]:
np.subtract(20,10)

10

<font size = 5>Multiplication</font>

In [15]:
np.multiply(a,b)

200

<font size = 5>Division</font>

In [16]:
np.divide(b,a)

2.0

In [7]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)

In [18]:
np.add(arr1,arr2)

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [19]:
np.sum([arr1,arr2])

180

In [21]:
np.subtract(arr2,arr1)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [22]:
np.multiply(arr1,arr2)

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [23]:
np.divide(arr1,arr2)

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

<font size = 5>Exponent</font>

In [26]:
np.exp(arr2)

array([[5.98741417e+04, 1.62754791e+05, 4.42413392e+05],
       [1.20260428e+06, 3.26901737e+06, 8.88611052e+06],
       [2.41549528e+07, 6.56599691e+07, 1.78482301e+08]])

<font size = 5>Square Root</font>

In [27]:
np.sqrt(arr2)

array([[3.31662479, 3.46410162, 3.60555128],
       [3.74165739, 3.87298335, 4.        ],
       [4.12310563, 4.24264069, 4.35889894]])

<font size = 5>Sine</font>

In [28]:
np.sin(arr1)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

<font size = 5>Cosine</font>

In [29]:
np.cos(arr2)

array([[ 0.0044257 ,  0.84385396,  0.90744678],
       [ 0.13673722, -0.75968791, -0.95765948],
       [-0.27516334,  0.66031671,  0.98870462]])

<font size = 5>Logarithm</font>

In [8]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

<font size = 6>Array Comparison</font>

<font size = 5>2 types:</font>

<font size = 5>Element-wise</font>

<font size = 4>Compares all elements in the arrays</font>

In [2]:
a = [1,2,4]
b = [2,4,6]
c = [1,2,4]
np.equal(a,b)

array([False, False, False])

In [3]:
a = [1,2,4]
b = [2,4,6]
c = [1,2,4]
np.equal(a,c)

array([ True,  True,  True])

<font size = 5>Array-wise</font>

<font size = 4>Compares whole array</font>

In [4]:
a = [1,2,4]
b = [2,4,4]
c = [1,2,4]
np.array_equal(a,c)

True

In [5]:
a = [1,2,4]
b = [2,4,4]
c = [1,2,4]
np.array_equal(a,b)

False

<font size = 5>Aggregate Function</font>

<font size = 4>Mean,Median,Max,Min</font>

In [9]:
a = [1,2,4]
b = [2,4,4]
c = [1,2,4]
np.mean(a)

2.3333333333333335

In [10]:
np.median(b)

4.0

In [11]:
np.max(c)

4

In [13]:
np.corrcoef(b)

1.0

In [14]:
np.std(b)

0.9428090415820634

<font size = 5>Numpy Broadcasting</font>

In [17]:
arr1 = np.array([[0,0,0],[1,2,3],[4,5,6],[5,6,7]])
arr2 = np.array([[0,1,2]])
print('First array : \n',arr1,'\n')
print('Second array : \n',arr2,'\n')
print('First array + Second array : \n',arr1 + arr2)

First array : 
 [[0 0 0]
 [1 2 3]
 [4 5 6]
 [5 6 7]] 

Second array : 
 [[0 1 2]] 

First array + Second array : 
 [[0 1 2]
 [1 3 5]
 [4 6 8]
 [5 7 9]]


<font size = 6>Array Manipulation</font>

<font size = 5>Concatenating two arrays together</font>

In [18]:
arr3 = np.array([1,2,3])
arr4 = np.array([4,5,6])
np.concatenate((arr3,arr4))

array([1, 2, 3, 4, 5, 6])

<font size = 5>Stack arrays column-wise(horizontally)</font>

In [ ]:
arr3 = np.array([1,2,3])
arr4 = np.array([4,5,6])
arr4 = np.array([4,5,6])
np.hstack((arr3,arr4))

array([1, 2, 3, 4, 5, 6])

<font size = 5>Stack arrays row-wise(vertically)</font>

In [24]:
arr3 = np.array([1,2,3])
arr4 = np.array([4,5,6])
arr4 = np.array([4,5,6])
np.vstack((arr3,arr4))

array([[1, 2, 3],
       [4, 5, 6]])

<font size = 5>Combinig column wise stacked array</font>

In [34]:
arr3 = np.array([1,2,3])
arr4 = np.array([4,5,6])
np.vstack((arr3,arr4))

array([[1, 2, 3],
       [4, 5, 6]])

<font size = 5>Spliting array</font>

In [26]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
np.hsplit(x,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [32]:
np.hsplit(x,np.array([3,6]))

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([], shape=(4, 0), dtype=int64)]

In [33]:
np.hsplit(x,np.array([2,3]))

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [ ]:
np.vsplit(x,np.array([3,6]))

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([], shape=(0, 4), dtype=int64)]

In [81]:
y=np.random.randint(1,20,size=(6,6))
z=np.random.randint(11,30,size=(6,6))
print(y)
print(z)

[[ 9 17 11  8  8  9]
 [ 8 17 16 12  4 19]
 [15 17  3  7 17 19]
 [19 11  5  8  6 15]
 [13  6 13  4  6 11]
 [ 9 14 18 13 11  1]]
[[23 23 14 12 24 12]
 [29 22 23 23 19 13]
 [14 17 19 29 29 28]
 [21 22 16 14 29 11]
 [21 17 16 11 19 16]
 [28 25 26 25 25 21]]


In [65]:
np.vsplit(y,(2,3))

[array([[14, 15,  2,  5, 15, 15],
        [11,  5,  9,  2,  7,  1]]),
 array([[ 1, 17, 16, 17, 13, 10]]),
 array([[10, 17, 18,  6, 12,  4],
        [ 9,  4,  2, 17,  8,  4],
        [17, 11, 10, 19,  6,  5]])]

In [66]:
np.hsplit(y,(3,2))

[array([[14, 15,  2],
        [11,  5,  9],
        [ 1, 17, 16],
        [10, 17, 18],
        [ 9,  4,  2],
        [17, 11, 10]]),
 array([], shape=(6, 0), dtype=int64),
 array([[ 2,  5, 15, 15],
        [ 9,  2,  7,  1],
        [16, 17, 13, 10],
        [18,  6, 12,  4],
        [ 2, 17,  8,  4],
        [10, 19,  6,  5]])]

In [67]:
np.vstack((y,z))

array([[14, 15,  2,  5, 15, 15],
       [11,  5,  9,  2,  7,  1],
       [ 1, 17, 16, 17, 13, 10],
       [10, 17, 18,  6, 12,  4],
       [ 9,  4,  2, 17,  8,  4],
       [17, 11, 10, 19,  6,  5],
       [25, 19, 15, 29, 24, 18],
       [17, 11, 20, 17, 26, 13],
       [22, 24, 25, 11, 28, 26],
       [23, 26, 27, 11, 17, 12],
       [19, 23, 16, 24, 21, 16],
       [16, 23, 26, 22, 14, 26]])

In [68]:
np.hstack((z,y))

array([[25, 19, 15, 29, 24, 18, 14, 15,  2,  5, 15, 15],
       [17, 11, 20, 17, 26, 13, 11,  5,  9,  2,  7,  1],
       [22, 24, 25, 11, 28, 26,  1, 17, 16, 17, 13, 10],
       [23, 26, 27, 11, 17, 12, 10, 17, 18,  6, 12,  4],
       [19, 23, 16, 24, 21, 16,  9,  4,  2, 17,  8,  4],
       [16, 23, 26, 22, 14, 26, 17, 11, 10, 19,  6,  5]])

In [69]:
np.add(y,z)

array([[39, 34, 17, 34, 39, 33],
       [28, 16, 29, 19, 33, 14],
       [23, 41, 41, 28, 41, 36],
       [33, 43, 45, 17, 29, 16],
       [28, 27, 18, 41, 29, 20],
       [33, 34, 36, 41, 20, 31]])

In [70]:
np.subtract(z,y)

array([[11,  4, 13, 24,  9,  3],
       [ 6,  6, 11, 15, 19, 12],
       [21,  7,  9, -6, 15, 16],
       [13,  9,  9,  5,  5,  8],
       [10, 19, 14,  7, 13, 12],
       [-1, 12, 16,  3,  8, 21]])

In [71]:
np.multiply(z,y)

array([[350, 285,  30, 145, 360, 270],
       [187,  55, 180,  34, 182,  13],
       [ 22, 408, 400, 187, 364, 260],
       [230, 442, 486,  66, 204,  48],
       [171,  92,  32, 408, 168,  64],
       [272, 253, 260, 418,  84, 130]])

In [72]:
np.divide(z,y)

array([[ 1.78571429,  1.26666667,  7.5       ,  5.8       ,  1.6       ,
         1.2       ],
       [ 1.54545455,  2.2       ,  2.22222222,  8.5       ,  3.71428571,
        13.        ],
       [22.        ,  1.41176471,  1.5625    ,  0.64705882,  2.15384615,
         2.6       ],
       [ 2.3       ,  1.52941176,  1.5       ,  1.83333333,  1.41666667,
         3.        ],
       [ 2.11111111,  5.75      ,  8.        ,  1.41176471,  2.625     ,
         4.        ],
       [ 0.94117647,  2.09090909,  2.6       ,  1.15789474,  2.33333333,
         5.2       ]])

In [73]:
np.log(y)

array([[2.63905733, 2.7080502 , 0.69314718, 1.60943791, 2.7080502 ,
        2.7080502 ],
       [2.39789527, 1.60943791, 2.19722458, 0.69314718, 1.94591015,
        0.        ],
       [0.        , 2.83321334, 2.77258872, 2.83321334, 2.56494936,
        2.30258509],
       [2.30258509, 2.83321334, 2.89037176, 1.79175947, 2.48490665,
        1.38629436],
       [2.19722458, 1.38629436, 0.69314718, 2.83321334, 2.07944154,
        1.38629436],
       [2.83321334, 2.39789527, 2.30258509, 2.94443898, 1.79175947,
        1.60943791]])

In [74]:
np.exp(z)

array([[7.20048993e+10, 1.78482301e+08, 3.26901737e+06, 3.93133430e+12,
        2.64891221e+10, 6.56599691e+07],
       [2.41549528e+07, 5.98741417e+04, 4.85165195e+08, 2.41549528e+07,
        1.95729609e+11, 4.42413392e+05],
       [3.58491285e+09, 2.64891221e+10, 7.20048993e+10, 5.98741417e+04,
        1.44625706e+12, 1.95729609e+11],
       [9.74480345e+09, 1.95729609e+11, 5.32048241e+11, 5.98741417e+04,
        2.41549528e+07, 1.62754791e+05],
       [1.78482301e+08, 9.74480345e+09, 8.88611052e+06, 2.64891221e+10,
        1.31881573e+09, 8.88611052e+06],
       [8.88611052e+06, 9.74480345e+09, 1.95729609e+11, 3.58491285e+09,
        1.20260428e+06, 1.95729609e+11]])

In [75]:
np.sin(y)

array([[ 0.99060736,  0.65028784,  0.90929743, -0.95892427,  0.65028784,
         0.65028784],
       [-0.99999021, -0.95892427,  0.41211849,  0.90929743,  0.6569866 ,
         0.84147098],
       [ 0.84147098, -0.96139749, -0.28790332, -0.96139749,  0.42016704,
        -0.54402111],
       [-0.54402111, -0.96139749, -0.75098725, -0.2794155 , -0.53657292,
        -0.7568025 ],
       [ 0.41211849, -0.7568025 ,  0.90929743, -0.96139749,  0.98935825,
        -0.7568025 ],
       [-0.96139749, -0.99999021, -0.54402111,  0.14987721, -0.2794155 ,
        -0.95892427]])

In [76]:
np.cos(z)

array([[ 0.99120281,  0.98870462, -0.75968791, -0.74805753,  0.42417901,
         0.66031671],
       [-0.27516334,  0.0044257 ,  0.40808206, -0.27516334,  0.64691932,
         0.90744678],
       [-0.99996083,  0.42417901,  0.99120281,  0.0044257 , -0.96260587,
         0.64691932],
       [-0.53283302,  0.64691932, -0.29213881,  0.0044257 , -0.27516334,
         0.84385396],
       [ 0.98870462, -0.53283302, -0.95765948,  0.42417901, -0.54772926,
        -0.95765948],
       [-0.95765948, -0.53283302,  0.64691932, -0.99996083,  0.13673722,
         0.64691932]])

In [77]:
np.sort(y)

array([[ 2,  5, 14, 15, 15, 15],
       [ 1,  2,  5,  7,  9, 11],
       [ 1, 10, 13, 16, 17, 17],
       [ 4,  6, 10, 12, 17, 18],
       [ 2,  4,  4,  8,  9, 17],
       [ 5,  6, 10, 11, 17, 19]])

In [78]:
z.dot(y)

array([[1386, 1512, 1211, 1342, 1351,  846],
       [1004, 1186,  941, 1238, 1082,  703],
       [1401, 1460, 1174, 1619, 1335,  890],
       [1102, 1321, 1064, 1209, 1218,  813],
       [1236, 1340, 1135, 1218, 1206,  728],
       [1291, 1513, 1339, 1432, 1271,  797]])

<font size = 6>Indexing And Slicing</font>

<font size = 5>Index refers to a position</font>

In [84]:
z[0,2]

14

In [87]:
p = np.array([[1,2,3],[4,5,6,],[7,8,9]])
p

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
p[0]

array([1, 2, 3])

In [88]:
p[:1]

array([[1, 2, 3]])

In [89]:
p[:1,1:]

array([[2, 3]])

In [90]:
p[:2,1:]

array([[2, 3],
       [5, 6]])

In [91]:
p[1:,1:]

array([[5, 6],
       [8, 9]])

In [95]:
p[1:,0:2]

array([[4, 5],
       [7, 8]])

<font size = 6>Advantages of Numpy array Over the list</font>

<font size = 5>1. Consumes less memory</font>

In [3]:
import sys

In [4]:
lst = range(1000)

In [5]:
arr = np.arange(1000)

In [6]:
print('Size of  list: ', sys.getsizeof(1)*len(lst))
print('size of an array :', arr.size*arr.itemsize)

Size of  list:  28000
size of an array : 8000


<font size = 5>2. Faster</font>

<font size = 5>3. More convenient</font>

In [1]:
import time

In [10]:
def using_lst():
    t1 = time.time()        #starting/Initial time
    x = range(10000)
    y = range(10000)
    z = [x[i]+y[i] for i in range(len(x))]
    return time.time()-t1
def using_np():
    t1 = time.time()        #starting/Initial time
    a = np.arange(10000)
    b = np.arange(10000)
    z = a + b               # more convenient than a lst
    return time.time()-t1
lst_time =using_lst()
np_time = using_np()
print(lst_time,'\n',np_time)
print('In this example np is : ' + str(lst_time/np_time)+' faster than a lst.')

0.0016078948974609375 
 3.4809112548828125e-05
In this example np is : 46.19178082191781 faster than a lst.


<font size = 6>Introduction to Scipy</font>

<font size = 6>What is SciPy?</font>

<font size = 5>Free and open-source Python library.</font>

<font size = 5>Used for scientific computing and technical computing.</font>

<font size = 5>Contains modules for optimization, linear algebra, integration, interpolation, special functions, FFT, signal and image processing.</font>

<font size = 6>Characteristics of SciPy</font>

<font size = 5>1. Contains toolboxes dedicated to common issues in scientific computing.</font>

<font size = 5>2. Different submodules corresponds to different applications.</font>

<font size = 5>3. Operators on NumPy array, NumPy adn SciPy work hand in hand.</font>

<font size = 5>4. Adds significant power to the interactive Python session.</font>

<font size = 5>5. Routine are tested and optimized.</font>

<font size = 6>Sub-Packages in SciPy</font>

<font size = 5>scipy.cluster</font>

<font size = 5>scipy.stats</font>

<font size = 5>scipy.optimize</font>

<font size = 5>scipy.integrate</font>

<font size = 5>scipy.linalg</font>

<font size = 5>scipy.fftpack</font>

<font size = 5>scipy.signal</font>

<font size = 6>scipy.cluster</font>

<font size = 5>Why do we use scipy.cluster()</font>

<font size = 4>It provides kmeans() function</font>

<font size = 4>Useful while driving data into clusters of related attributes</font>

<font size = 4>Divide n observations into k clusters</font>

<font size = 5>What is clustering?</font>

<font size = 5>grouping of similar items in one signal group</font>

<font size = 5>How do we find clusters?</font>

<font size = 5>Step 1: Randomly select two cluster centers</font>

<font size = 5>Step 2: Assign members to the cluster</font>

<font size = 5>Step 3: Calculate the mean distance of each member</font>

<font size = 5>Step 4: Shift the cluster center towards mean, Repeat Step 2 and Step 3</font>

In [ ]:
import pandas as pd
from scipy.cluster.vq import kmeans,vq
data = pd.read_excel('/Users/ritikramesh/Documents/Python/PYINT/CLASSES/Pandas Hands_on/cust_dimen.csv')
centroid,_ = kmeans(data,3)
idx,_ =vq(data,centroid)
idx

In [ ]:
print(centroid)